- name: Adds Tmux Repo
  sudo_user: root
  command: add-apt-repository -y ppa:pi-rho/dev creates=/etc/apt/sources.list.d/pi-rho-dev-trusty.list

- name: Update Apt Cache
  sudo_user: root
  apt: update_cache=yes cache_valid_time=86400

- name: Install Essentials
  sudo_user: root
  apt: name={{ item.name }} state=latest
  with_items:
    - { name: 'git' }
    - { name: 'build-essential' }
    - { name: 'python-dev' }
    - { name: 'python-pip' }
    - { name: 'python3-dev' }
    - { name: 'python3-pip' }
    - { name: 'cmake' }

- name: Install Build Essentials
  sudo_user: root
  apt: name=build-essential state=latest

- name: Set up Tools Directory
  file: path=~/.tools state=directory
