- name: Install Go
  sudo_user: root
  tags: test
  script: ../scripts/install_go.sh {{ go_version }} creates=/usr/local/go

- name: Set up Go src directory
  file: path=/code/go/src state=directory recurse=yes

- name: set up go bin directory
  file: path=/code/go/bin state=directory recurse=yes

- name: set up go pkg directory
  file: path=/code/go/pkg state=directory recurse=yes
