- name: Install Go
  sudo_user: root
  script: ../scripts/install_go.sh {{ go_version }} creates=/usr/local/go

- name: Set up Go Directories
  file: path={{ workspace_dir }}/go/{{ item.name }} state=directory recurse=yes
  with_items:
    - { name: 'src' }
    - { name: 'pkg' }
    - { name: 'bin' }

- name: Set up Go Essentials
  command: go get -u -v {{ item.address }} creates={{ workspace_dir }}/go/bin/{{ item.name }}
  with_items:
    - { name: 'gocode', address: 'github.com/nsf/gocode'}
    - { name: 'goimports', address: 'golang.org/x/tools/cmd/goimports'}
    - { name: 'godef', address: 'github.com/rogpeppe/godef'}
    - { name: 'oracle', address: 'golang.org/x/tools/cmd/oracle'}
    - { name: 'gorename', address: 'golang.org/x/tools/cmd/gorename'}
    - { name: 'golint', address: 'github.com/golang/lint/golint'}
    - { name: 'errcheck', address: 'github.com/kisielk/errcheck'}
    - { name: 'gotags', address: 'github.com/jstemmer/gotags'}
