- name: Prime apt to download latest Nodejs
  sudo_user: root
  script: ../scripts/prime_apt_nodejs.sh creates=/etc/apt/sources.list.d/nodesource.list

- name: Set up Nodejs
  sudo_user: root
  apt: name=nodejs state=latest

- name: Latest NPM
  sudo_user: root
  npm: name=npm state=latest global=true

- name: Install JsHint
  sudo_user: root
  npm: name=jshint state=latest global=true
