- name: Install Ruby-Install
  sudo_user: root
  script: ../scripts/install_ruby_install.sh {{ ruby_install_version }} creates=/usr/local/bin/ruby-install

- name: Install Chruby
  sudo_user: root
  script: ../scripts/install_chruby.sh {{ chruby_version }} creates=/usr/local/bin/chruby-exec

- name: Install Latest Ruby
  shell: cd /tmp && ruby-install ruby {{ ruby_version }} --no-reinstall creates=~/.rubies/ruby-2.2.0

- name: Install Bundler system wide
  sudo_user: root
  gem:
    name: bundler
    user_install: no


