- name: Install Tmux
  sudo_user: root
  apt: name=tmux state=latest

- name: Set up Tmux SSH config
  sudo_user: "{{ user_name }}"
  template: src=../templates/ssh-tmux.rc dest=~/.ssh/rc

- name: Install Tmux Plugin Manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Install Tmuxinator
  sudo_user: root
  gem:
    name: tmuxinator
    user_install: no

- name: Set up Ag
  sudo_user: root
  script: ../scripts/install_ag.sh creates=/usr/bin/ag

- name: Set up Jq
  sudo_user: root
  apt: name=jq state=latest

- name: Set up AWS CLI
  sudo_user: root
  pip: name=awscli state=latest

