- name: Install Tmux
  sudo_user: root
  apt: name=tmux state=latest

- name: Set up Tmux SSH config
  sudo_user: vagrant
  template: src=../templates/ssh-tmux.rc dest=~/.ssh/rc

- name: Install Tmux Plugin Manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Install Tmuxinator
  sudo_user: root
  gem:
    name: tmuxinator
    user_install: no

- name: Install Peco
  tags: test
  script: ../scripts/install_peco.sh {{ peco_version }} creates=/usr/local/bin/peco

- name: Set up Peco Config Dir
  file: path=~/.peco state=directory

- name: Set up Peco Config
  template: src=../templates/peco.json dest=~/.peco/config.json

- name: Set up Ag
  sudo_user: root
  apt: name=silversearcher-ag state=latest

