- name: Install Neovim
  sudo_user: root
  apt: name=neovim state=latest

- name: Set up Vim Bundle Directory
  file: path=~/.vim/bundle/ recurse=true state=directory

- name: Install Neobundle
  git: repo=https://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim

- name: Set up NVimrc
  template: src=./../templates/vimrc.vim dest=~/.nvimrc

- name: Set up Vim Bundle
  template: src=./../templates/vim.bundle dest=~/.vim.bundle

- name: Install Vim Plugins
  command: ~/.vim/bundle/neobundle.vim/bin/neoinstall
