- name: Uninstall Stock Vim
  sudo_user: root
  apt: name=vim state=absent

- name: Install Neovim
  sudo_user: root
  apt: name=neovim state=latest

- name: Install Neovim Python Support
  sudo_user: root
  pip: name=neovim state=latest

- name: Set up Vim Bundle Directory
  file: path=~/.vim/bundle/ recurse=true state=directory

- name: Install Neobundle
  git: repo=https://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim

- name: Set up NVimrc
  template: src=./../templates/vimrc.vim dest=~/.nvimrc

- name: Set up Vim Bundle
  template: src=./../templates/vim.bundle dest=~/.vim.bundle

- name: Install Vim Plugins
  script: ../scripts/install_vim_plugins.sh creates=~/.vim/bundle/vimproc.vim

- name: Compile YCM
  command: ~/.vim/bundle/YouCompleteMe/install.sh creates=~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so
