PostCheckout:
 ALL:
   quiet: false

 IndexTags:
   enabled: true

PostRewrite:
  IndexTags:
    enabled: true

PostMerge:
  IndexTags:
    enabled: true

PreCommit:
  AnsibleNoCurrentTags:
    enabled: true
