- name: Set up work space directory
  become: yes
  become_user: root
  file: path={{ workspace_dir }} state=directory

- name: Mount work space directory
  become: yes
  become_user: root
  shell: mount {{ workspace_dev }} {{ workspace_dir }}

