- name: Install Virtualbox
  homebrew_cask: name=virtualbox state=present

- name: Install Vagrant
  homebrew_cask: name=vagrant state=present

- name: Set up Workspace
  file: path={{ workspace_dir }}/ state=directory recurse=yes

- name: Install Ag
  homebrew: name=ag state=present

- name: Common Config Files
  template: src=./dev-box/templates/{{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'ack.rc', dest: '~/.ackrc' }
    - { src: 'gem.rc', dest: '~/.gemrc' }
    - { src: 'gitconfig.rc', dest: '~/.gitconfig' }
    - { src: 'tmux.rc', dest: '~/.tmux.conf' }
    - { src: 'top.rc', dest: '~/.toprc' }
    - { src: 'rspec.rc', dest: '~/.rspec' }
    - { src: 'ctags.rc', dest: '~/.ctags' }
    - { src: 'ghci.rc', dest: '~/.ghci' }
    - { src: 'inputrc.bash', dest: '~/.inputrc' }
