---

- name: Set up Workspace
  file: path={{ workspace_dir }}/ state=directory recurse=yes

- name: Install Virtualbox/Vagrant
  homebrew_cask: name="{{ item }}" state=present
  with_items:
  - virtualbox
  - vagrant

- name: Install Pip
  become: yes
  become_user: root
  easy_install: name=pip state=latest

- name: Install Coreutils/Python3/Wget/Ag/RipGrep/Fzf/Bash Completion/Progress/Tmux/htop/Tree
  homebrew: name="{{ item }}" state=present
  with_items:
  - coreutils
  - python3
  - wget
  - ag
  - ripgrep
  - fzf
  - bash-completion
  - progress
  - tmux
  - htop
  - tree
  - awscli
  - jq
  - watchman

- name: Set up .config dir
  file: path=~/.config recurse=true state=directory

- name: Set up yamllint config dir
  file: path=~/.config/yamllint recurse=true state=directory

- name: Common Config Files
  template: src=./dev-box/templates/{{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'gem.rc'                  , dest: '~/.gemrc' }
    - { src: 'gitconfig.rc'            , dest: '~/.gitconfig' }
    - { src: 'git/gitignore_global.rc' , dest: '~/.gitignore_global' }
    - { src: 'tmux.rc'                 , dest: '~/.tmux.conf' }
    - { src: 'top.rc'                  , dest: '~/.toprc' }
    - { src: 'rspec.rc'                , dest: '~/.rspec' }
    - { src: 'ctags.rc'                , dest: '~/.ctags' }
    - { src: 'ghci.rc'                 , dest: '~/.ghci' }
    - { src: 'inputrc.bash'            , dest: '~/.inputrc' }
    - { src: 'pushover.conf'           , dest: '~/.config/pushover.conf' }
    - { src: 'yamllint.yaml'           , dest: '~/.config/yamllint/config' }

- name: VS Code Settings
  template: src=./mac/templates/{{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '../templates/vs-code-settings.json'   , dest: '~/Library/Application Support/Code/User/settings.json' }
    - { src: '../templates/vs-code-keybindings.json', dest: '~/Library/Application Support/Code/User/keybindings.json' }
