---

- name: Set up Workspace
  file: path={{ workspace_dir }}/ state=directory recurse=yes

- name: Install Virtualbox/Vagrant
  homebrew_cask: name="{{ item }}" state=present
  with_items:
  - virtualbox
  - vagrant

- name: Install Coreutils/Wget/Ag/Fzf/Bash Completion/Progress/Tmux/htop
  homebrew: name="{{ item }}" state=present
  with_items:
  - coreutils
  - wget
  - ag
  - fzf
  - bash-completion
  - progress
  - tmux
  - htop

- name: Set up .config dir
  file: path=~/.config recurse=true state=directory

- name: Set up yamllint config dir
  file: path=~/.config/yamllint recurse=true state=directory

- name: Common Config Files
  template: src=./dev-box/templates/{{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'ack.rc'                  , dest: '~/.ackrc' }
    - { src: 'gem.rc'                  , dest: '~/.gemrc' }
    - { src: 'gitconfig.rc'            , dest: '~/.gitconfig' }
    - { src: 'git/gitignore_global.rc' , dest: '~/.gitignore_global' }
    - { src: 'tmux.rc'                 , dest: '~/.tmux.conf' }
    - { src: 'top.rc'                  , dest: '~/.toprc' }
    - { src: 'rspec.rc'                , dest: '~/.rspec' }
    - { src: 'ctags.rc'                , dest: '~/.ctags' }
    - { src: 'ghci.rc'                 , dest: '~/.ghci' }
    - { src: 'inputrc.bash'            , dest: '~/.inputrc' }
    - { src: 'pushover.conf'           , dest: '~/.config/pushover.conf' }
    - { src: 'yamllint.yaml'           , dest: '~/.config/yamllint/config' }
