- name: Install Emacs
  homebrew: name=emacs state=head

- name: Cron for Emacs Server
  become: yes
  cron: special_time=reboot job="emacs --daemon >/dev/null 2>&1" name="emacs_daemon" user="{{ user_name }}"
