- name: Copy Devbox Public Key
  become_user: "{{ user_name }}"
  authorized_key: user={{ user_name }} key={{ item }} state=present exclusive=yes
  with_file:
    - ./mac/public_keys/devbox.pub

- name: Capture vagrant ssh config
  local_action: shell vagrant ssh-config --host devbox
  register: vagrant_ssh_config_raw

- name: Ensure SSH Config file exists
  file: path=~/.ssh/config state=touch mode="u=rw,g=r,o=r"

- name: Add Devbox ssh config
  blockinfile:
    dest: ~/.ssh/config
    content: "{{ vagrant_ssh_config_raw.stdout }}"
    state: present

- name: Add Reverse proxy for ssh
  lineinfile: dest=~/.ssh/config line="RemoteForward 2702 127.0.0.1:2702" state=present
