---
- hosts: mac
  roles:
    - mac
  become_user: "{{ user_name }}"
  vars_files:
    - ./dev-box/vars/software_version_vars.yml
    - ./dev-box/vars/git_vars.yml
    - ./dev-box/vars/encrypted_vars.yml
  vars:
    timezone: Australia/Melbourne
    guest_machine: false
