- name: Add PPAs
  become: yes
  become_user: root
  command: sudo add-apt-repository -y ppa:{{ item.name }} creates=/etc/apt/sources.list.d/{{ item.filename }}-wily.list
  with_items:
    - {name: 'neovim-ppa/unstable', filename: 'neovim-ppa-ubuntu-unstable'}
    - {name: 'pi-rho/dev', filename: 'pi-rho-ubuntu-dev' }

- name: Update Apt Cache
  become: yes
  become_user: root
  apt: update_cache=yes cache_valid_time=86400

- name: Install Essentials
  become: yes
  become_user: root
  apt: name={{ item }} state=latest
  with_items:
    - ntp
    - language-pack-en
    - git
    - build-essential
    - python-dev
    - python3-dev
    - python3-pip
    - default-jre
    - default-jdk
    - cmake
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev
    - ruby-dev
    - libxslt-dev
    - libxml2-dev
    - upower
    - mercurial

- name: Install correct Pip
  become: yes
  become_user: root
  easy_install: name=pip state=latest

- name: Install Python Virtualenv
  become: yes
  become_user: root
  pip: name=virtualenv state=latest

- name: Common Config Files
  template: src=./dev-box/templates/{{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'ack.rc',        dest: '~/.ackrc' }
    - { src: 'gem.rc',        dest: '~/.gemrc' }
    - { src: 'gitconfig.rc',  dest: '~/.gitconfig' }
    - { src: 'ssh-tmux.rc',   dest: '~/.ssh-tmux.rc' }
    - { src: 'tmux.rc',       dest: '~/.tmux.conf' }
    - { src: 'top.rc',        dest: '~/.toprc' }
    - { src: 'rspec.rc',      dest: '~/.rspec' }
    - { src: 'ctags.rc',      dest: '~/.ctags' }
    - { src: 'ghci.rc',       dest: '~/.ghci' }
    - { src: 'haskeline.rc',  dest: '~/.haskeline' }
    - { src: 'inputrc.bash',  dest: '~/.inputrc' }

- name: Set up Timezone
  become: yes
  become_user: root
  command: "{{ item }}"
  with_items:
    - sudo timedatectl set-timezone {{ timezone }}
    - ln -sf /usr/share/zoneinfo/{{ timezone }} /etc/localtime
