- name: Install Docker
  become: yes
  become_user: root
  script: ./dev-box/scripts/install_docker.sh creates=/usr/bin/docker

- name: Set up Docker Group
  become: yes
  become_user: root
  command: usermod -aG docker {{ user_name }}

- name: Install Docker Compose
  become: yes
  become_user: root
  pip: name=docker-compose state=latest
