- name: Add Stack Haskell GPG
  become: yes
  become_user: root
  apt_key: keyserver=keyserver.ubuntu.com id=575159689BEFB442

- name: Add Haskell Stack Apt Source
  become: yes
  become_user: root
  apt_repository: repo='deb http://download.fpcomplete.com/ubuntu wily main' state=present update_cache=yes

- name: Install Stack Haskell
  become: yes
  apt: name=stack state=latest

- name: Stack Global Setup
  command: stack setup chdir=~/ creates=~/.stack/global-project/stack.yaml

- name: Set up GHCI color
  git: repo=https://github.com/premjg/ghci-color.git dest=~/.ghci-color

- name: Set up Essential Haskell Packages
  command: stack install {{ item }} creates=~/.local/bin/{{ item }}
  with_items:
  - hdevtools
  - ghc-mod
  - hlint
  - HUnit

- name: Correct File Permissions for .ghci
  become: yes
  become_user: "{{ user_name }}"
  file: path=~/.ghci mode="g-w"

