- name: Set up Tmux SSH config
  become: yes
  become_user: "{{ user_name }}"
  template: src=./dev-box/templates/ssh-tmux.rc dest=~/.ssh/rc

- name: Install Tmux Plugin Manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Install Tmuxinator
  become: yes
  become_user: root
  gem:
    name: tmuxinator
    user_install: no

- name: Set up Tmuxinator Dir
  file: path=~/.tmuxinator state=directory recurse=yes

- name: Set up Tmuxinator templates
  template: src=./dev-box/templates/tmuxinator/{{ item }}.yml dest=~/.tmuxinator/{{ item }}.yml
  with_items:
    - haskell
    - javascript
    - ruby
