- name: Install Neovim Python Support
  become: yes
  become_user: root
  pip: name=neovim state=latest

- name: Set up Vim Bundle Directory
  file: path=~/.config/nvim/bundle/ recurse=true state=directory

- name: Install Neobundle
  git: repo=https://github.com/Shougo/neobundle.vim dest=~/.config/nvim/bundle/neobundle.vim

- name: Set up Vim Bundle
  template: src=./dev-box/templates/vim.bundle dest=~/.config/nvim/.bundle

- name: Set up Minimal Bundle Vimrc
  template: src=./dev-box/templates/vimrc.bundleonly dest=~/.config/nvim/init.vim

- name: Install Vim Plugins
  shell: nvim --headless -c 'NeoBundleUpdate | qall!' creates=~/.config/nvim/bundle/vimproc.vim

- name: Compile YCM
  script: ./dev-box/scripts/compile_ycm.sh creates=~/.config/nvim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so

- name: Set up NVimrc
  template: src=./dev-box/templates/vimrc.vim dest=~/.config/nvim/init.vim
