# - name: Install Neovim Python Support
#   become: yes
#   become_user: "{{ user_name }}"
#   pip: name=neovim state=latest

- name: Set up Vim Autoload Directory
  file: path=~/.config/nvim/autoload/ recurse=true state=directory

- name: Set up Vim Undo Directory
  file: path=~/.config/nvim/undo/ recurse=true state=directory

- name: Install Vimplug
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.config/nvim/autoload/plug.vim

- name: Set up NVimrc
  template: src=./dev-box/templates/vimrc.vim dest=~/.config/nvim/init.vim

- name: Set up Vim Plugs
  template: src=./dev-box/templates/vim.plugs dest=~/.config/nvim/.plugs

- name: Install Vim Plugins
  shell: nvim --headless -c 'PlugInstall | qall!'
