- name: Uninstall Stock Vim
  become: yes
  become_user: root
  apt: name=vim state=absent

- name: Install Neovim
  become: yes
  become_user: root
  apt: name=neovim state=latest

- name: Set up Neovim as Default
  become: yes
  become_user: root
  alternatives: name={{ item }} link=/usr/bin/{{ item }} path=/usr/bin/nvim
  with_items:
    - vi
    - vim
    - editor
